name: claw
on: workflow_dispatch
jobs:
  claw:
    runs-on: ubuntu-24.04-arm
    steps:
      - run: |
          curl -fsSL https://openclaw.ai/install-cli.sh | bash
          ~/.openclaw/bin/openclaw config set providers.gemini.apiKey "AIzaSyAggonkHDJQLcXlvzWyLW9jotGRTwKJx24"
          ~/.openclaw/bin/openclaw config set models.default "gemini-3-flash"
          ~/.openclaw/bin/openclaw config set channels.telegram.botToken "8746891105:AAEXzLKMlPNVHMN6kLpO11fDJlRFlFeI_2s"
          ~/.openclaw/bin/openclaw config set security.sandbox false
          ~/.openclaw/bin/openclaw gateway restart
